#app.yaml
runtime: python27
api_version: 1  
threadsafe: true

handlers:
- url: /styleDir
  static_dir: styleDir

- url: /images
  static_dir: images

- url: /javaS
  static_dir: javaS

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest












